name: CI on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windowsbuild:
    runs-on: windows-2019
    steps:
      - name: Set xmake global dir
        run: |
          echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/.xmake-global" >> "${{ github.env }}"
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.7
      - name: update repo
        run: xmake repo -u
      - name: git crlf
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      # Force xmake to a specific folder (for cache)
      - name: config
        run: xmake config --yes -vD
      - name: build
        run: xmake build --yes -vD
      - name: test
        run: xmake test
