name: Lint

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Data/**'
      - 'Kernel/**'
      - 'tests/**'
      - '.github/workflows/clang-format-linter.yml'
      - 'xmake.lua' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        exclude: './build ./xmake ./workflow ./github'
        extensions: 'hpp,cpp'
        clangFormatVersion: 16
        style: file