name: Bug 报告
description: 报告问题以帮助我们改进
labels: 'bug'
body:

- type: input
  attributes:
    label: Mogan 版本
    description: 你正在使用的 Mogan 版本是什么？
    placeholder: 0.0.0
  validations:
    required: true

- type: input
  attributes:
    label: 操作系统版本和架构
    description: 你正在使用的操作系统版本和架构是什么? 在 Windows 上，请点击 开始按钮 > 设置 > 系统 > 关于。在 macOS 上，点击左上角苹果菜单 > 关于本机。在 Linux 上，使用 lsb_release 或者 uname -a 命令查看。
    placeholder: "例如：Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04"
  validations:
    required: true

- type: textarea
  attributes:
    label: 描述问题
    description: 请尽量清晰精准地描述你碰到的问题。
  validations:
    required: true

- type: textarea
  attributes:
    label: 期待的结果
    description: 请尽量清晰精准地描述你所期待的结果。
  validations:
    required: true

