name: 请求新功能
description: 提出你期待的功能特性
labels: 'feature request'
body:

- type: textarea
  id: problem
  attributes:
    label: 你在什么场景下需要该功能？
    description: 请尽量清晰精准地描述你碰到的问题。
  validations:
    required: true

- type: textarea
  id: solution
  attributes:
    label: 描述可能的解决方案
    description: 请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。
  validations:
    required: true

- type: textarea
  id: second-solution
  attributes:
    label: 描述你认为的候选方案
    description: 请尽量清晰精准地描述你能接受的候选解决方案。

- type: textarea
  id: other
  attributes:
    label: 其他信息
    description: 请提供关于该功能建议的其他附加信息。
