version: '1.0'
name: ci-check-code-format
displayName: ci-check-code-format
triggers:
  trigger: auto
  pr:
    branches:
      precise:
        - main
    paths:
      precise:
        - .workflow/ci-check-code-format.yml
        - .clang-format
        - src/
        - tests/
        - 3rdparty/moebius/
        - 3rdparty/lolly/
  push:
    branches:
      precise:
        - main
    paths:
      precise:
        - .workflow/ci-check-code-format.yml
        - .clang-format
        - src/
        - tests/
        - 3rdparty/moebius/
        - 3rdparty/lolly/

stages:
  - name: check_code_format
    displayName: check_code_format
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: execute@docker
        name: execute_by_docker
        displayName: use clang-format-16 to check code format
        certificate: ''
        image: docker.1ms.run/amd64/debian:trixie
        command:
          - bash .workflow/ustc_debian822_setup.sh
          - apt-get update
          - apt-get install -y clang-format-19
          - clang-format-19 --version
          - shopt -s nullglob globstar
          - clang-format-19 --dry-run --Werror tests/**/*.cpp
          - clang-format-19 --dry-run --Werror tests/**/*.hpp
          - clang-format-19 --dry-run --Werror src/**/*.cpp
          - clang-format-19 --dry-run --Werror src/**/*.hpp
          - clang-format-19 --dry-run --Werror 3rdparty/moebius/**/*.hpp
          - clang-format-19 --dry-run --Werror 3rdparty/moebius/**/*.cpp
          - clang-format-19 --dry-run --Werror 3rdparty/lolly/**/*.hpp
          - clang-format-19 --dry-run --Werror 3rdparty/lolly/**/*.cpp
        notify: []
        strategy:
          retry: '0'
          stepTimeout: 15

