
("(re)build autocompletion index" "构建/重建自动补全索引")
("GNU TeXmacs comes without any form of legal warranty" "GNU TeXmacs 无任何形式的法律保证")
("GNU TeXmacs falls under the GNU general public license" "GNU TeXmacs 使用 GNU 通用公共许可授权")
("a series" "A系列")
("abbreviation" "缩写")
("about menu" "关于菜单")
("about" "关于")
("activate once" "仅激活一次")
("activate" "激活")
("activation" "激活")
("add branch after" "在后面添加一个")
("add branch before" "在前面添加一个")
("add other package" "增加其他宏包")
("american" "美式英语")
("and" "与")
("angular" "角")
("animate objects" "设置动画效果")
("animate" "动画")
("animated" "有动画")
("animation toolbar" "动画工具栏")
("animation" "动画")
("answer" "答案")
("arithmetic" "算术")
("armenian" "亚美尼亚语")
("arrow" "箭头")
("arrow-with-text" "带文本的箭头")
("arrow-with-text*" "带文本的箭头*")
("arrows" "箭头")
("article" "文章")
("as on paper" "如同在纸上一样的")
("begin" "开始")
("below" "下面")
("beta release" "β 版")
("bezier" "贝塞尔曲线")
("bibliography file" "参考文献文件")
("bibliography style" "参考文献的样式文件")
("bibliography text" "参考文献目录名")
("bytes used" "使用 bytes 总数")
("calculus" "微积分")
("calligraphic" "书法字体")
("calligraphy" "书法")
("cancel" "取消")
("cartesian" "直角坐标")
("case" "")
("close this document" "关闭当前文档")
("close window" "关闭窗口")
("close" "退出")
("closed bezier" "闭合贝塞尔曲线")
("closed curve" "闭合曲线")
("closed smooth" "闭合平滑曲线")
("closed spline" "闭合样条曲线")
("closing style" "结束风格")
("closing" "")
("creating technical pictures" "内置作图工具")
("croatian" "克罗地亚语")
("crop" "剪裁")
("cross" "叉号")
("current graphical mode" "当前绘图模式")
("current version" "当前版本")
("cursors" "游标")
("curve intersections" "曲线交点")
("curve points" "曲线点")
("curve" "曲线")
("custom tab" "自定义制表符")
("custom tab" "自定义制表符")
("developer tool" "开发工具")
("developer" "开发者")
("developers guide" "程序源码")
("diamond" "菱形")
("directory" "目录")
("disable first indentation after" "")
("disable first indentation before" "")
("encryption" "加密")
("end" "结束")
("english" "英语")
("enhance" "增强")
("enter a title" "输入标题")
("enter data" "输入数据")
("entire column" "整列")
("execute" "运行")
("executive" "行政")
("exercise" "练习")
("exit graphics mode" "退出绘图模式")
("exit left" "从左边跳出")
("exit right" "从右边跳出")
("exit tag on the left" "从左边跳出")
("extern " "")
("extra" "")
("extract format" "")
("fade in" "淡入")
("fade out" "淡出")
("family" "")
("fast decrease" "快速减小")
("fast increase" "快速增大")
("february" "")
("field" "区域")
("figure" "图")
("grain" "粒度")
("graphical effects" "图形效果")
("graphical interface" "图形界面")
("graphics geometry" "画布设置")
("graphics grids" "网格设置")
("graphics overlay" "图形遮罩")
("graphics" "图形")
("grave" "")
("greater or equal" "大于等于")
("greek" "希腊语")
("green" "绿色")
("grey" "灰色")
("grid lines" "网格线")
("grid points" "网格点")
("grid" "网格")
("grid-curve intersections" "网格与曲线的交点")
("grids" "网格")
("group" "")
("group/ungroup" "分组/打散")
("improving the current implementation" "改进当前的实作")
("in popup windows" "在弹出窗口")
("inactive" "")
("inanimated" "无动画")
("include a document" "")
("include file" "")
("include" "包含文件")
("index level" "下标层次")
("index" "索引")
("informative flags" "非正式标记")
("ink in" "上墨")
("ink out" "去墨")
("inline arguments" "行内参数")
("inline code" "行内代码")
("inline formula" "行内公式")
("layout" "布局")
("left aligned" "左对齐")
("left arrow" "")
("left arrow" "左箭头")
("left axis" "左轴线")
("left baseline" "左侧基线")
("left border" "左端")
("left buttom" "左下")
("left cell border" "")
("left cell padding" "")
("left center" "左中")
("left margin" "左边距")
("left padding" "")
("left prime" "")
("left surrounding" "")
("left table border" "")
("left table padding" "")
("left top" "左上")
("left" "左")
("leftwards" "往左边")
("legal" "法律")
("lemma" "引理")
("line breaking" "断行算法")
("line properties" "线属性")
("line stretch" "")
("line style" "线条样式")
("line width" "线宽度")
("line wrapping" "自动换行")
("line" "线")
("logarithmic" "对数坐标")
("logarithms" "对数")
("login" "登录")
("long text" "长文本")
("long text" "长文本")
("long" "细长")
("look and feel" "快捷键风格")
("look for more fonts" "查找更多字体")
("look up" "")
("loops" "圈")
("lower border" "下端")
("m modifier" "")
("macro" "宏命令")
("maximum mode" "")
("maximum" "最大值")
("may" "")
("meander" "蜿蜒")
("medium skip" "中间距")
("medium" "适中")
("meminfo" "")
("month" "月")
("more information about GNU TeXmacs can be found in the Help" "更多关于 GNU TeXmacs 的信息可查看帮助")
("mosaic" "")
("motif" "主题")
("move down" "")
("move object" "")
("move objects" "移动对象")
("move to the right when finished" "输入完成后移动光标到右边")
("move up" "")
("move" "移动")
("orange" "橙色")
("orientation" "方向")
("origin" "原点")
("origin's x-coordinate:" "原点的x坐标")
("origin's y-coordinate:" "原点的y坐标")
("origin's" "原点的")
("original welcome message" "欢迎信息")
("other package" "其它宏包")
("other pages" "其它页")
("output options" "输出选项")
("over" "")
("overbrace" "")
("overlay" "遮罩")
("overline" "上划线")
("overview of the scheme extension language" "Scheme 扩展语言概览")
("padding" "补白")
("path" "")
("pdf version number" "PDF版本号")
("pen width" "笔宽")
("penscript" "笔迹")
("perform operations on cells" "对单元格操作")
("perform operations on columns" "对整列操作")
("perform operations on entire table" "对整个表格操作")
("plugin" "插件")
("plugins" "插件")
("plus" "")
("plus" "加号")
("point style" "点形状")
("point" "点")
("polar" "极坐标")
("proposition" "命题")
("pseudo code" "伪代码")
("publisher" "出版者")
("pulse" "脉冲")
("query replace" "替换文本")
("question" "问题")
("question" "问题")
("recent documents" "最近文档")
("recent" "最近使用")
("recover autosave file" "复元自动保存文件")
("rectangle" "矩形")
("red" "红色")
("redo undone changes" "恢复更改")
("redo" "恢复")
("replace" "替换")
("replaced one occurrence" "")
("replaced" "")
("repulse" "边距")
("reset" "重置")
("resize object" "")
("resize objects" "缩放对象")
("resize" "改变大小")
("resized" "")
("retain" "保留")
("revert" "恢复")
("right aligned" "右对齐")
("right arrow" "")
("right arrow" "右箭头")
("right baseline" "右侧基线")
("right border" "右端")
("right cell border" "")
("right surrounding" "")
("right table border" "")
("right table padding" "")
("right" "右")
("rightwards" "往右边")
("rigid horizontal" "")
("rigid space" "")
("root" "根")
("rotate backward" "")
("rotate forward" "")
("rotate objects" "旋转对象")
("rotate" "旋转")
("rough" "粗糙")
("round" "圆圈")
("set paragraph mode" "段落对齐")
("set printer dpi" "")
("set printing command" "")
("set properties" "设置属性")
("set span" "设置合并")
("set special cell properties" "设定单元格特殊属性")
("set special table properties" "设定表格特殊属性")
("slanted" "倾斜")
("sloppy" "粗略")
("slovene" "斯洛文尼亚语")
("slow decrease" "慢速减小")
("slow decrease" "慢速增大")
("small caps" "小体大写")
("small figure" "小图片标题")
("small skip" "小间距")
("small table" "小表格")
("small" "小")
("smooth" "平滑")
("smooth" "平滑曲线")
("snap distance" "吸附距离")
("snap" "自动吸附设置")
("solution" "解答")
("solving equations" "解方程")
("songti" "宋体")
("standard environment variables" "标准的环境变量")
("standard formats" "标准格式")
("standard" "标准")
("star" "五角星")
("start a new chapter" "新起一章")
("start a new section" "新起一节")
("start an interactive session" "插入交互会话")
("start" "开始")
("statistics" "统计")
("status bar" "状态栏")
("status" "状态")
("status: " "状态:")
("storage" "存储")
("stretch factor" "拉伸因子")
("stretch" "拉伸")
("ternary" "")
("test" "检测")
("tex" "")
("text borders" "文本边界")
("text box alignment" "文本框对齐")
("text box horizontal alignment" "文本框水平对齐")
("text box vertical alignment" "文本框竖直对齐")
("text box" "文本框")
("text corners" "文本角")
("text font" "文本字体")
("text height correction" "文本高度修正")
("text width" "")
("this page" "")
("this row" "此行")
("three times" "三次")
("three-points-circle" "三点画圆")
("through popup windows" "通过弹出窗口")
("through the menus" "通过菜单")
("thumbnails" "缩略图")
("unit length" "单位长度")
("unit" "单位")
("up" "")
("up" "上")
("update from web" "")
("update image links" "")
("update this buffer" "更新此缓冲区")
("visual grid" "可视网格")
("volume" "卷")
("warning" "警告")
("wave" "波浪")
("web" "网站")
("welcome to GNU TeXmacs" "欢迎使用 GNU TeXmacs")
("welcome" "欢迎")
("writing documentation" "编写插件文档")
("writing your own style files" "编写自己的样式文件")
("written with TeXmacs" "使用 TeXmacs 制作")
("x-coordinate" "x坐标")
("y-coordinate" "y坐标")
("year" "年")
("yellow" "黄色")
("yes" "是")
("you can also obtain" "")
("your document is back in its original state" "")
("your first interface" "")
("your language" "使用语言")
("zigzag" "之字形")
("zoom factor" "缩放比例")
("zoom in" "放大")
("zoom out" "缩小")