
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;
;; MODULE      : text-kbd-utf8.scm
;; DESCRIPTION : keystrokes in text mode
;; COPYRIGHT   : (C) 2024   Darcy Shen
;;
;; This software falls under the GNU general public license version 3 or later.
;; It comes WITHOUT ANY WARRANTY WHATSOEVER. For details, see the file LICENSE
;; in the root directory or <http://www.gnu.org/licenses/gpl-3.0.html>.
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(texmacs-module (text text-kbd-utf8)
  (:use (generic generic-kbd)
        (utils edit auto-close)
        (text text-edit)
        (various comment-edit)
        (various comment-widgets)))

(kbd-map
  (:mode in-text?)
  ("<" "<less>")
  (">" "<gtr>")
  ("< var" "<#2039>")
  ("> var" "<#203A>"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Greek symbols
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(kbd-map
  ("alpha" "<#3B1>")
  ("beta" "<#3B2>")
  ("gamma" "<#3B3>")
  ("delta" "<#3B4>")
  ("epsilon" "<#3F5>")
  ("varepsilon" "<#3B5>")
  ("zeta" "<#3B6>")
  ("eta" "<#3B7>")
  ("theta" "<#3B8>")
  ("vartheta" "<#3D1>")
  ("iota" "<#3B9>")
  ("kappa" "<#3BA>")
  ("varkappa" "<#3F0>")
  ("lambda" "<#3BB>")
  ("mu" "<#3BC>")
  ("nu" "<#3BD>")
  ("xi" "<#3BE>")
  ("omicron" "<#3BF>")
  ("pi" "<#3C0>")
  ("varpi" "<#3D6>")
  ("rho" "<#3C1>")
  ("varrho" "<#3F1>")
  ("sigma" "<#3C3>")
  ("varsigma" "<#3C2>")
  ("tau" "<#3C4>")
  ("upsilon" "<#3C5>")
  ("phi" "<#3C6>")
  ("varphi" "<#3D5>")
  ("chi" "<#3C7>")
  ("psi" "<#3C8>")
  ("omega" "<#3C9>")
  ("Alpha" "<#391>")
  ("Beta" "<#392>")
  ("Gamma" "<#393>")
  ("Delta" "<#394>")
  ("Epsilon" "<#395>")
  ("Zeta" "<#396>")
  ("Eta" "<#397>")
  ("Theta" "<#398>")
  ("Iota" "<#399>")
  ("Kappa" "<#39A>")
  ("Lambda" "<#39B>")
  ("Mu" "<#39C>")
  ("Nu" "<#39D>")
  ("Xi" "<#39E>")
  ("Omicron" "<#39F>")
  ("Pi" "<#3A0>")
  ("Rho" "<#3A1>")
  ("Sigma" "<#3A3>")
  ("Tau" "<#3A4>")
  ("Upsilon" "<#3A5>")
  ("Phi" "<#3A6>")
  ("Chi" "<#3A7>")
  ("Psi" "<#3A8>")
  ("Omega" "<#3A9>")
  (": + 1 :" "<#1F44D>")
  (": - 1 :" "<#1F44E>")
  (": 1 0 0 :" "<#1F4AF>")
  (": 1 2 3 4 :" "<#1F522>")
  (": 8 b a l l :" "<#1F3B1>")
  (": a b c :" "<#1F524>")
  (": a b c d :" "<#1F521>")
  (": a e r i a l t r a m w a y :" "<#1F6A1>")
  (": a i r p l a n e :" "<#2708>")
  (": a l i e n :" "<#1F47D>")
  (": a m b u l a n c e :" "<#1F691>")
  (": a n c h o r :" "<#2693>")
  (": a n g e l :" "<#1F47C>")
  (": a n g e r :" "<#1F4A2>")
  (": a n g r y :" "<#1F620>")
  (": a n g u i s h e d :" "<#1F627>")
  (": a n t :" "<#1F41C>")
  (": a p p l e :" "<#1F34E>")
  (": a q u a r i u s :" "<#2652>")
  (": a r i e s :" "<#2648>")
  (": a r r o w b a c k w a r d :" "<#25C0>")
  (": a r r o w d o w n :" "<#2B07>")
  (": a r r o w d o w n s m a l l :" "<#1F53D>")
  (": a r r o w f o r w a r d :" "<#25B6>")
  (": a r r o w h e a d i n g d o w n :" "<#2935>")
  (": a r r o w h e a d i n g u p :" "<#2934>")
  (": a r r o w l e f t :" "<#2B05>")
  (": a r r o w l o w e r l e f t :" "<#2199>")
  (": a r r o w l o w e r r i g h t :" "<#2198>")
  (": a r r o w r i g h t :" "<#27A1>")
  (": a r r o w r i g h t h o o k :" "<#21AA>")
  (": a r r o w u p :" "<#2B06>")
  (": a r r o w u p d o w n :" "<#2195>")
  (": a r r o w u p s m a l l :" "<#1F53C>")
  (": a r r o w u p p e r l e f t :" "<#2196>")
  (": a r r o w u p p e r r i g h t :" "<#2197>")
  (": a r r o w s c l o c k w i s e :" "<#1F503>")
  (": a r r o w s c o u n t e r c l o c k w i s e :" "<#1F504>")
  (": a r t :" "<#1F3A8>")
  (": a r t i c u l a t e d l o r r y :" "<#1F69B>")
  (": a s t o n i s h e d :" "<#1F632>")
  (": a t m :" "<#1F3E7>")
  (": b a b y :" "<#1F476>")
  (": b a b y b o t t l e :" "<#1F37C>")
  (": b a b y c h i c k :" "<#1F424>")
  (": b a b y s y m b o l :" "<#1F6BC>")
  (": b a g g a g e c l a i m :" "<#1F6C4>")
  (": b a l l o o n :" "<#1F388>")
  (": b a l l o t b o x w i t h c h e c k :" "<#2611>")
  (": b a m b o o :" "<#1F38D>")
  (": b a n a n a :" "<#1F34C>")
  (": b a n g b a n g :" "<#203C>")
  (": b a n k :" "<#1F3E6>")
  (": b a r c h a r t :" "<#1F4CA>")
  (": b a r b e r :" "<#1F488>")
  (": b a s e b a l l :" "<#26BE>")
  (": b a s k e t b a l l :" "<#1F3C0>")
  (": b a t h :" "<#1F6C0>")
  (": b a t h t u b :" "<#1F6C1>")
  (": b a t t e r y :" "<#1F50B>")
  (": b e a r :" "<#1F43B>")
  (": b e e r :" "<#1F37A>")
  (": b e e r s :" "<#1F37B>")
  (": b e e t l e :" "<#1FAB2>")
  (": b e g i n n e r :" "<#1F530>")
  (": b e l l :" "<#1F514>")
  (": b e n t o :" "<#1F371>")
  (": b i c y c l i s t :" "<#1F6B4>")
  (": b i k e :" "<#1F6B2>")
  (": b i k i n i :" "<#1F459>")
  (": b i r d :" "<#1F426>")
  (": b i r t h d a y :" "<#1F382>")
  (": b l a c k c i r c l e :" "<#26AB>")
  (": b l a c k n i b :" "<#2712>")
  (": b l a c k s q u a r e b u t t o n :" "<#1F532>")
  (": b l o s s o m :" "<#1F33C>")
  (": b l o w f i s h :" "<#1F421>")
  (": b l u e b o o k :" "<#1F4D8>")
  (": b l u e c a r :" "<#1F699>")
  (": b l u e h e a r t :" "<#1F499>")
  (": b l u s h :" "<#1F60A>")
  (": b o a r :" "<#1F417>")
  (": b o a t :" "<#26F5>")
  (": b o m b :" "<#1F4A3>")
  (": b o o k :" "<#1F4D6>")
  (": b o o k m a r k :" "<#1F516>")
  (": b o o k m a r k t a b s :" "<#1F4D1>")
  (": b o o k s :" "<#1F4DA>")
  (": b o o m :" "<#1F4A5>")
  (": b o o t :" "<#1F462>")
  (": b o u q u e t :" "<#1F490>")
  (": b o w :" "<#1F647>")
  (": b o w l i n g :" "<#1F3B3>")
  (": b o y :" "<#1F466>")
  (": b r e a d :" "<#1F35E>")
  (": b r i d e w i t h v e i l :" "<#1F470>")
  (": b r i d g e a t n i g h t :" "<#1F309>")
  (": b r i e f c a s e :" "<#1F4BC>")
  (": b r o k e n h e a r t :" "<#1F494>")
  (": b u g :" "<#1F41B>")
  (": b u l b :" "<#1F4A1>")
  (": b u l l e t t r a i n f r o n t :" "<#1F685>")
  (": b u l l e t t r a i n s i d e :" "<#1F684>")
  (": b u s :" "<#1F68C>")
  (": b u s s t o p :" "<#1F68F>")
  (": b u s t i n s i l h o u e t t e :" "<#1F464>")
  (": b u s t s i n s i l h o u e t t e :" "<#1F465>")
  (": c a c t u s :" "<#1F335>")
  (": c a k e :" "<#1F370>")
  (": c a l e n d a r :" "<#1F4C6>")
  (": c a l l i n g :" "<#1F4F2>")
  (": c a m e l :" "<#1F42B>")
  (": c a m e r a :" "<#1F4F7>")
  (": c a n c e r :" "<#264B>")
  (": c a n d y :" "<#1F36C>")
  (": c a p i t a l a b c d :" "<#1F520>")
  (": c a p r i c o r n :" "<#2651>")
  (": c a r :" "<#1F697>")
  (": c a r d i n d e x :" "<#1F4C7>")
  (": c a r o u s e l h o r s e :" "<#1F3A0>")
  (": c a t :" "<#1F431>")
  (": c a t 2 :" "<#1F408>")
  (": c d :" "<#1F4BF>")
  (": c h a r t :" "<#1F4B9>")
  (": c h a r t w i t h d o w n w a r d s t r e n d :" "<#1F4C9>")
  (": c h a r t w i t h u p w a r d s t r e n d :" "<#1F4C8>")
  (": c h e c k e r e d f l a g :" "<#1F3C1>")
  (": c h e r r i e s :" "<#1F352>")
  (": c h e r r y b l o s s o m :" "<#1F338>")
  (": c h e s t n u t :" "<#1F330>")
  (": c h i c k e n :" "<#1F414>")
  (": c h i l d r e n c r o s s i n g :" "<#1F6B8>")
  (": c h o c o l a t e b a r :" "<#1F36B>")
  (": c h r i s t m a s t r e e :" "<#1F384>")
  (": c h u r c h :" "<#26EA>")
  (": c i n e m a :" "<#1F3A6>")
  (": c i r c u s t e n t :" "<#1F3AA>")
  (": c i t y s u n r i s e :" "<#1F307>")
  (": c i t y s u n s e t :" "<#1F306>")
  (": c l a p :" "<#1F44F>")
  (": c l a p p e r :" "<#1F3AC>")
  (": c l i p b o a r d :" "<#1F4CB>")
  (": c l o c k 1 :" "<#1F550>")
  (": c l o c k 1 0 :" "<#1F559>")
  (": c l o c k 1 0 3 0 :" "<#1F565>")
  (": c l o c k 1 1 :" "<#1F55A>")
  (": c l o c k 1 1 3 0 :" "<#1F566>")
  (": c l o c k 1 2 :" "<#1F55B>")
  (": c l o c k 1 2 3 0 :" "<#1F567>")
  (": c l o c k 1 3 0 :" "<#1F55C>")
  (": c l o c k 2 :" "<#1F551>")
  (": c l o c k 2 3 0 :" "<#1F55D>")
  (": c l o c k 3 :" "<#1F552>")
  (": c l o c k 3 3 0 :" "<#1F55E>")
  (": c l o c k 4 :" "<#1F553>")
  (": c l o c k 4 3 0 :" "<#1F55F>")
  (": c l o c k 5 :" "<#1F554>")
  (": c l o c k 5 3 0 :" "<#1F560>")
  (": c l o c k 6 :" "<#1F555>")
  (": c l o c k 6 3 0 :" "<#1F561>")
  (": c l o c k 7 :" "<#1F556>")
  (": c l o c k 7 3 0 :" "<#1F562>")
  (": c l o c k 8 :" "<#1F557>")
  (": c l o c k 8 3 0 :" "<#1F563>")
  (": c l o c k 9 :" "<#1F558>")
  (": c l o c k 9 3 0 :" "<#1F564>")
  (": c l o s e d b o o k :" "<#1F4D5>")
  (": c l o s e d l o c k w i t h k e y :" "<#1F510>")
  (": c l o s e d u m b r e l l a :" "<#1F302>")
  (": c l o u d :" "<#2601>")
  (": c l u b s :" "<#2663>")
  (": c n :" "<#1F1E8>")
  (": c o c k t a i l :" "<#1F378>")
  (": c o f f e e :" "<#2615>")
  (": c o l d s w e a t :" "<#1F630>")
  (": c o l l i s i o n :" "<#1F4A5>")
  (": c o m p u t e r :" "<#1F4BB>")
  (": c o n f e t t i b a l l :" "<#1F38A>")
  (": c o n f o u n d e d :" "<#1F616>")
  (": c o n f u s e d :" "<#1F615>")
  (": c o n s t r u c t i o n :" "<#1F6A7>")
  (": c o n s t r u c t i o n w o r k e r :" "<#1F477>")
  (": c o n v e n i e n c e s t o r e :" "<#1F3EA>")
  (": c o o k i e :" "<#1F36A>")
  (": c o p :" "<#1F46E>")
  (": c o p y r i g h t :" "<#00A9>")
  (": c o r n :" "<#1F33D>")
  (": c o u p l e :" "<#1F46B>")
  (": c o u p l e w i t h h e a r t :" "<#1F491>")
  (": c o u p l e k i s s :" "<#1F48F>")
  (": c o w :" "<#1F42E>")
  (": c o w 2 :" "<#1F404>")
  (": c r e d i t c a r d :" "<#1F4B3>")
  (": c r o c o d i l e :" "<#1F40A>")
  (": c r o s s e d f l a g s :" "<#1F38C>")
  (": c r o w n :" "<#1F451>")
  (": c r y :" "<#1F622>")
  (": c r y i n g c a t f a c e :" "<#1F63F>")
  (": c r y s t a l b a l l :" "<#1F52E>")
  (": c u p i d :" "<#1F498>")
  (": c u r l y l o o p :" "<#27B0>")
  (": c u r r e n c y e x c h a n g e :" "<#1F4B1>")
  (": c u r r y :" "<#1F35B>")
  (": c u s t a r d :" "<#1F36E>")
  (": c u s t o m s :" "<#1F6C3>")
  (": c y c l o n e :" "<#1F300>")
  (": d a n c e r :" "<#1F483>")
  (": d a n c e r s :" "<#1F46F>")
  (": d a n g o :" "<#1F361>")
  (": d a r t :" "<#1F3AF>")
  (": d a s h :" "<#1F4A8>")
  (": d a t e :" "<#1F4C5>")
  (": d e :" "<#1F1E9>")
  (": d e c i d u o u s t r e e :" "<#1F333>")
  (": d e p a r t m e n t s t o r e :" "<#1F3EC>")
  (": d i a m o n d s h a p e w i t h a d o t i n s i d e :" "<#1F4A0>")
  (": d i a m o n d s :" "<#2666>")
  (": d i s a p p o i n t e d :" "<#1F61E>")
  (": d i s a p p o i n t e d r e l i e v e d :" "<#1F625>")
  (": d i z z y :" "<#1F4AB>")
  (": d i z z y f a c e :" "<#1F635>")
  (": d o n o t l i t t e r :" "<#1F6AF>")
  (": d o g :" "<#1F436>")
  (": d o g 2 :" "<#1F415>")
  (": d o l l a r :" "<#1F4B5>")
  (": d o l l s :" "<#1F38E>")
  (": d o l p h i n :" "<#1F42C>")
  (": d o o r :" "<#1F6AA>")
  (": d o u g h n u t :" "<#1F369>")
  (": d r a g o n :" "<#1F409>")
  (": d r a g o n f a c e :" "<#1F432>")
  (": d r e s s :" "<#1F457>")
  (": d r o m e d a r y c a m e l :" "<#1F42A>")
  (": d r o p l e t :" "<#1F4A7>")
  (": d v d :" "<#1F4C0>")
  (": e m a i l :" "<#1F4E7>")
  (": e a r :" "<#1F442>")
  (": e a r o f r i c e :" "<#1F33E>")
  (": e a r t h a f r i c a :" "<#1F30D>")
  (": e a r t h a m e r i c a s :" "<#1F30E>")
  (": e a r t h a s i a :" "<#1F30F>")
  (": e g g :" "<#1F95A>")
  (": e g g p l a n t :" "<#1F346>")
  (": e i g h t p o i n t e d b l a c k s t a r :" "<#2734>")
  (": e i g h t s p o k e d a s t e r i s k :" "<#2733>")
  (": e l e c t r i c p l u g :" "<#1F50C>")
  (": e l e p h a n t :" "<#1F418>")
  (": e m a i l :" "<#1F4E7>")
  (": e n d :" "<#1F51A>")
  (": e n v e l o p e :" "<#2709>")
  (": e s :" "<#1F1EA>")
  (": e u r o :" "<#1F4B6>")
  (": e u r o p e a n c a s t l e :" "<#1F3F0>")
  (": e u r o p e a n p o s t o f f i c e :" "<#1F3E4>")
  (": e v e r g r e e n t r e e :" "<#1F332>")
  (": e x c l a m a t i o n :" "<#2757>")
  (": e x p r e s s i o n l e s s :" "<#1F611>")
  (": e y e g l a s s e s :" "<#1F453>")
  (": e y e s :" "<#1F440>")
  (": f a c e p u n c h :" "<#1F44A>")
  (": f a c t o r y :" "<#1F3ED>")
  (": f a l l e n l e a f :" "<#1F342>")
  (": f a m i l y :" "<#1F46A>")
  (": f a x :" "<#1F4E0>")
  (": f e a r f u l :" "<#1F628>")
  (": f e e t :" "<#1F43E>")
  (": f e r r i s w h e e l :" "<#1F3A1>")
  (": f i l e f o l d e r :" "<#1F4C1>")
  (": f i r e :" "<#1F525>")
  (": f i r e e n g i n e :" "<#1F692>")
  (": f i r e w o r k s :" "<#1F386>")
  (": f i r s t q u a r t e r m o o n :" "<#1F313>")
  (": f i r s t q u a r t e r m o o n w i t h f a c e :" "<#1F31B>")
  (": f i s h :" "<#1F41F>")
  (": f i s h c a k e :" "<#1F365>")
  (": f i s h i n g p o l e a n d f i s h :" "<#1F3A3>")
  (": f i s t :" "<#270A>")
  (": f l a g s :" "<#1F38F>")
  (": f l a s h l i g h t :" "<#1F526>")
  (": f l o p p y d i s k :" "<#1F4BE>")
  (": f l o w e r p l a y i n g c a r d s :" "<#1F3B4>")
  (": f l u s h e d :" "<#1F633>")
  (": f o g g y :" "<#1F301>")
  (": f o o t b a l l :" "<#1F3C8>")
  (": f o r k a n d k n i f e :" "<#1F374>")
  (": f o u n t a i n :" "<#26F2>")
  (": f o u r l e a f c l o v e r :" "<#1F340>")
  (": f r :" "<#1F1EB>")
  (": f r i e d s h r i m p :" "<#1F364>")
  (": f r i e s :" "<#1F35F>")
  (": f r o g :" "<#1F438>")
  (": f r o w n i n g :" "<#1F626>")
  (": f u :" "<#1F595>")
  (": f u e l p u m p :" "<#26FD>")
  (": f u l l m o o n :" "<#1F315>")
  (": f u l l m o o n w i t h f a c e :" "<#1F31D>")
  (": g a m e d i e :" "<#1F3B2>")
  (": g b :" "<#1F1EC>")
  (": g e m :" "<#1F48E>")
  (": g e m i n i :" "<#264A>")
  (": g h o s t :" "<#1F47B>")
  (": g i f t :" "<#1F381>")
  (": g i f t h e a r t :" "<#1F49D>")
  (": g i r l :" "<#1F467>")
  (": g l o b e w i t h m e r i d i a n s :" "<#1F310>")
  (": g o a t :" "<#1F410>")
  (": g o l f :" "<#26F3>")
  (": g r a p e s :" "<#1F347>")
  (": g r e e n a p p l e :" "<#1F34F>")
  (": g r e e n b o o k :" "<#1F4D7>")
  (": g r e e n h e a r t :" "<#1F49A>")
  (": g r e y e x c l a m a t i o n :" "<#2755>")
  (": g r e y q u e s t i o n :" "<#2754>")
  (": g r i m a c i n g :" "<#1F62C>")
  (": g r i n :" "<#1F601>")
  (": g r i n n i n g :" "<#1F600>")
  (": g u a r d s m a n :" "<#1F482>")
  (": g u i t a r :" "<#1F3B8>")
  (": g u n :" "<#1F52B>")
  (": h a i r c u t :" "<#1F487>")
  (": h a m b u r g e r :" "<#1F354>")
  (": h a m m e r :" "<#1F528>")
  (": h a m s t e r :" "<#1F439>")
  (": h a n d :" "<#270B>")
  (": h a n d b a g :" "<#1F45C>")
  (": h a n k e y :" "<#1F4A9>")
  (": h a s h :" "<#0023>")
  (": h a t c h e d c h i c k :" "<#1F425>")
  (": h a t c h i n g c h i c k :" "<#1F423>")
  (": h e a d p h o n e s :" "<#1F3A7>")
  (": h e a r n o e v i l :" "<#1F649>")
  (": h e a r t :" "<#2764>")
  (": h e a r t d e c o r a t i o n :" "<#1F49F>")
  (": h e a r t e y e s :" "<#1F60D>")
  (": h e a r t e y e s c a t :" "<#1F63B>")
  (": h e a r t b e a t :" "<#1F493>")
  (": h e a r t p u l s e :" "<#1F497>")
  (": h e a r t s :" "<#2665>")
  (": h e a v y c h e c k m a r k :" "<#2714>")
  (": h e a v y d i v i s i o n s i g n :" "<#2797>")
  (": h e a v y d o l l a r s i g n :" "<#1F4B2>")
  (": h e a v y e x c l a m a t i o n m a r k :" "<#2757>")
  (": h e a v y m i n u s s i g n :" "<#2796>")
  (": h e a v y m u l t i p l i c a t i o n x :" "<#2716>")
  (": h e a v y p l u s s i g n :" "<#2795>")
  (": h e l i c o p t e r :" "<#1F681>")
  (": h e r b :" "<#1F33F>")
  (": h i b i s c u s :" "<#1F33A>")
  (": h i g h b r i g h t n e s s :" "<#1F506>")
  (": h i g h h e e l :" "<#1F460>")
  (": h o c h o :" "<#1F52A>")
  (": h o n e y p o t :" "<#1F36F>")
  (": h o n e y b e e :" "<#1F41D>")
  (": h o r s e :" "<#1F434>")
  (": h o r s e r a c i n g :" "<#1F3C7>")
  (": h o s p i t a l :" "<#1F3E5>")
  (": h o t e l :" "<#1F3E8>")
  (": h o t s p r i n g s :" "<#2668>")
  (": h o u r g l a s s :" "<#231B>")
  (": h o u s e :" "<#1F3E0>")
  (": h o u s e w i t h g a r d e n :" "<#1F3E1>")
  (": h u s h e d :" "<#1F62F>")
  (": i c e c r e a m :" "<#1F368>")
  (": i c e c r e a m :" "<#1F366>")
  (": i m p :" "<#1F47F>")
  (": i n b o x t r a y :" "<#1F4E5>")
  (": i n c o m i n g e n v e l o p e :" "<#1F4E8>")
  (": i n f o r m a t i o n d e s k p e r s o n :" "<#1F481>")
  (": i n f o r m a t i o n s o u r c e :" "<#2139>")
  (": i n n o c e n t :" "<#1F607>")
  (": i n t e r r o b a n g :" "<#2049>")
  (": i p h o n e :" "<#1F4F1>")
  (": i t :" "<#1F1EE>")
  (": i z a k a y a l a n t e r n :" "<#1F3EE>")
  (": j a c k o l a n t e r n :" "<#1F383>")
  (": j a p a n :" "<#1F5FE>")
  (": j a p a n e s e c a s t l e :" "<#1F3EF>")
  (": j a p a n e s e g o b l i n :" "<#1F47A>")
  (": j a p a n e s e o g r e :" "<#1F479>")
  (": j e a n s :" "<#1F456>")
  (": j o y :" "<#1F602>")
  (": j o y c a t :" "<#1F639>")
  (": j p :" "<#1F1EF>")
  (": k e y :" "<#1F511>")
  (": k e y c a p t e n :" "<#1F51F>")
  (": k i m o n o :" "<#1F458>")
  (": k i s s :" "<#1F48B>")
  (": k i s s i n g :" "<#1F617>")
  (": k i s s i n g c a t :" "<#1F63D>")
  (": k i s s i n g c l o s e d e y e s :" "<#1F61A>")
  (": k i s s i n g h e a r t :" "<#1F618>")
  (": k i s s i n g s m i l i n g e y e s :" "<#1F619>")
  (": k o a l a :" "<#1F428>")
  (": k r :" "<#1F1F0>")
  (": l a r g e b l u e c i r c l e :" "<#1F535>")
  (": l a r g e b l u e d i a m o n d :" "<#1F537>")
  (": l a r g e o r a n g e d i a m o n d :" "<#1F536>")
  (": l a s t q u a r t e r m o o n :" "<#1F317>")
  (": l a s t q u a r t e r m o o n w i t h f a c e :" "<#1F31C>")
  (": l a u g h i n g :" "<#1F606>")
  (": l e a v e s :" "<#1F343>")
  (": l e d g e r :" "<#1F4D2>")
  (": l e f t l u g g a g e :" "<#1F6C5>")
  (": l e f t r i g h t a r r o w :" "<#2194>")
  (": l e f t w a r d s a r r o w w i t h h o o k :" "<#21A9>")
  (": l e m o n :" "<#1F34B>")
  (": l e o :" "<#264C>")
  (": l e o p a r d :" "<#1F406>")
  (": l i b r a :" "<#264E>")
  (": l i g h t r a i l :" "<#1F688>")
  (": l i n k :" "<#1F517>")
  (": l i p s :" "<#1F444>")
  (": l i p s t i c k :" "<#1F484>")
  (": l o c k :" "<#1F512>")
  (": l o c k w i t h i n k p e n :" "<#1F50F>")
  (": l o l l i p o p :" "<#1F36D>")
  (": l o o p :" "<#27BF>")
  (": l o u d s p e a k e r :" "<#1F4E2>")
  (": l o v e h o t e l :" "<#1F3E9>")
  (": l o v e l e t t e r :" "<#1F48C>")
  (": l o w b r i g h t n e s s :" "<#1F505>")
  (": m :" "<#24C2>")
  (": m a g :" "<#1F50D>")
  (": m a g r i g h t :" "<#1F50E>")
  (": m a i l b o x :" "<#1F4EB>")
  (": m a i l b o x c l o s e d :" "<#1F4EA>")
  (": m a i l b o x w i t h m a i l :" "<#1F4EC>")
  (": m a i l b o x w i t h n o m a i l :" "<#1F4ED>")
  (": m a n :" "<#1F468>")
  (": m a n w i t h g u a p i m a o :" "<#1F472>")
  (": m a n w i t h t u r b a n :" "<#1F473>")
  (": m a n s s h o e :" "<#1F45E>")
  (": m a p l e l e a f :" "<#1F341>")
  (": m a s k :" "<#1F637>")
  (": m a s s a g e :" "<#1F486>")
  (": m e a t o n b o n e :" "<#1F356>")
  (": m e g a :" "<#1F4E3>")
  (": m e l o n :" "<#1F348>")
  (": m e m o :" "<#1F4DD>")
  (": m e n s :" "<#1F6B9>")
  (": m e t a l :" "<#1F918>")
  (": m e t r o :" "<#1F687>")
  (": m i c r o p h o n e :" "<#1F3A4>")
  (": m i c r o s c o p e :" "<#1F52C>")
  (": m i l k y w a y :" "<#1F30C>")
  (": m i n i b u s :" "<#1F690>")
  (": m i n i d i s c :" "<#1F4BD>")
  (": m o b i l e p h o n e o f f :" "<#1F4F4>")
  (": m o n e y w i t h w i n g s :" "<#1F4B8>")
  (": m o n e y b a g :" "<#1F4B0>")
  (": m o n k e y :" "<#1F412>")
  (": m o n k e y f a c e :" "<#1F435>")
  (": m o n o r a i l :" "<#1F69D>")
  (": m o o n :" "<#1F314>")
  (": m o r t a r b o a r d :" "<#1F393>")
  (": m o u n t f u j i :" "<#1F5FB>")
  (": m o u n t a i n b i c y c l i s t :" "<#1F6B5>")
  (": m o u n t a i n c a b l e w a y :" "<#1F6A0>")
  (": m o u n t a i n r a i l w a y :" "<#1F69E>")
  (": m o u s e :" "<#1F42D>")
  (": m o u s e 2 :" "<#1F401>")
  (": m o v i e c a m e r a :" "<#1F3A5>")
  (": m o y a i :" "<#1F5FF>")
  (": m u s c l e :" "<#1F4AA>")
  (": m u s h r o o m :" "<#1F344>")
  (": m u s i c a l k e y b o a r d :" "<#1F3B9>")
  (": m u s i c a l n o t e :" "<#1F3B5>")
  (": m u s i c a l s c o r e :" "<#1F3BC>")
  (": m u t e :" "<#1F507>")
  (": n a i l c a r e :" "<#1F485>")
  (": n a m e b a d g e :" "<#1F4DB>")
  (": n e c k t i e :" "<#1F454>")
  (": n e g a t i v e s q u a r e d c r o s s m a r k :" "<#274E>")
  (": n e u t r a l f a c e :" "<#1F610>")
  (": n e w m o o n :" "<#1F311>")
  (": n e w m o o n w i t h f a c e :" "<#1F31A>")
  (": n e w s p a p e r :" "<#1F4F0>")
  (": n o b e l l :" "<#1F515>")
  (": n o b i c y c l e s :" "<#1F6B3>")
  (": n o e n t r y :" "<#26D4>")
  (": n o e n t r y s i g n :" "<#1F6AB>")
  (": n o g o o d :" "<#1F645>")
  (": n o m o b i l e p h o n e s :" "<#1F4F5>")
  (": n o m o u t h :" "<#1F636>")
  (": n o p e d e s t r i a n s :" "<#1F6B7>")
  (": n o s m o k i n g :" "<#1F6AD>")
  (": n o n p o t a b l e w a t e r :" "<#1F6B1>")
  (": n o s e :" "<#1F443>")
  (": n o t e b o o k :" "<#1F4D3>")
  (": n o t e b o o k w i t h d e c o r a t i v e c o v e r :" "<#1F4D4>")
  (": n o t e s :" "<#1F3B6>")
  (": n u t a n d b o l t :" "<#1F529>")
  (": o c e a n :" "<#1F30A>")
  (": o c t o p u s :" "<#1F419>")
  (": o d e n :" "<#1F362>")
  (": o f f i c e :" "<#1F3E2>")
  (": o k h a n d :" "<#1F44C>")
  (": o k w o m a n :" "<#1F646>")
  (": o l d e r m a n :" "<#1F474>")
  (": o l d e r w o m a n :" "<#1F475>")
  (": o n :" "<#1F51B>")
  (": o n c o m i n g a u t o m o b i l e :" "<#1F698>")
  (": o n c o m i n g b u s :" "<#1F68D>")
  (": o n c o m i n g p o l i c e c a r :" "<#1F694>")
  (": o n c o m i n g t a x i :" "<#1F696>")
  (": o p e n f i l e f o l d e r :" "<#1F4C2>")
  (": o p e n h a n d s :" "<#1F450>")
  (": o p e n m o u t h :" "<#1F62E>")
  (": o p h i u c h u s :" "<#26CE>")
  (": o r a n g e b o o k :" "<#1F4D9>")
  (": o u t b o x t r a y :" "<#1F4E4>")
  (": o x :" "<#1F402>")
  (": p a g e f a c i n g u p :" "<#1F4C4>")
  (": p a g e w i t h c u r l :" "<#1F4C3>")
  (": p a g e r :" "<#1F4DF>")
  (": p a l m t r e e :" "<#1F334>")
  (": p a n d a f a c e :" "<#1F43C>")
  (": p a p e r c l i p :" "<#1F4CE>")
  (": p a r t a l t e r n a t i o n m a r k :" "<#303D>")
  (": p a r t l y s u n n y :" "<#26C5>")
  (": p a s s p o r t c o n t r o l :" "<#1F6C2>")
  (": p a w p r i n t s :" "<#1F43E>")
  (": p e a c h :" "<#1F351>")
  (": p e a r :" "<#1F350>")
  (": p e n c i l :" "<#1F4DD>")
  (": p e n c i l 2 :" "<#270F>")
  (": p e n g u i n :" "<#1F427>")
  (": p e n s i v e :" "<#1F614>")
  (": p e r f o r m i n g a r t s :" "<#1F3AD>")
  (": p e r s e v e r e :" "<#1F623>")
  (": p h o n e :" "<#260E>")
  (": p i g :" "<#1F437>")
  (": p i g 2 :" "<#1F416>")
  (": p i g n o s e :" "<#1F43D>")
  (": p i l l :" "<#1F48A>")
  (": p i n e a p p l e :" "<#1F34D>")
  (": p i s c e s :" "<#2653>")
  (": p i z z a :" "<#1F355>")
  (": p o i n t d o w n :" "<#1F447>")
  (": p o i n t l e f t :" "<#1F448>")
  (": p o i n t r i g h t :" "<#1F449>")
  (": p o i n t u p :" "<#261D>")
  (": p o i n t u p 2 :" "<#1F446>")
  (": p o l i c e c a r :" "<#1F693>")
  (": p o o d l e :" "<#1F429>")
  (": p o o p :" "<#1F4A9>")
  (": p o s t o f f i c e :" "<#1F3E3>")
  (": p o s t a l h o r n :" "<#1F4EF>")
  (": p o s t b o x :" "<#1F4EE>")
  (": p o t a b l e w a t e r :" "<#1F6B0>")
  (": p o u c h :" "<#1F45D>")
  (": p o u l t r y l e g :" "<#1F357>")
  (": p o u n d :" "<#1F4B7>")
  (": p o u t i n g c a t :" "<#1F63E>")
  (": p r a y :" "<#1F64F>")
  (": p r i n c e s s :" "<#1F478>")
  (": p u n c h :" "<#1F44A>")
  (": p u r p l e h e a r t :" "<#1F49C>")
  (": p u r s e :" "<#1F45B>")
  (": p u s h p i n :" "<#1F4CC>")
  (": p u t l i t t e r i n i t s p l a c e :" "<#1F6AE>")
  (": q u e s t i o n :" "<#2753>")
  (": r a b b i t :" "<#1F430>")
  (": r a b b i t 2 :" "<#1F407>")
  (": r a c e h o r s e :" "<#1F40E>")
  (": r a d i o :" "<#1F4FB>")
  (": r a d i o b u t t o n :" "<#1F518>")
  (": r a g e :" "<#1F621>")
  (": r a i l w a y c a r :" "<#1F683>")
  (": r a i n b o w :" "<#1F308>")
  (": r a i s e d h a n d :" "<#270B>")
  (": r a i s e d h a n d s :" "<#1F64C>")
  (": r a i s i n g h a n d :" "<#1F64B>")
  (": r a m :" "<#1F40F>")
  (": r a m e n :" "<#1F35C>")
  (": r a t :" "<#1F400>")
  (": r e c y c l e :" "<#267B>")
  (": r e d c a r :" "<#1F697>")
  (": r e d c i r c l e :" "<#1F534>")
  (": r e g i s t e r e d :" "<#00AE>")
  (": r e l a x e d :" "<#263A>")
  (": r e l i e v e d :" "<#1F60C>")
  (": r e p e a t :" "<#1F501>")
  (": r e p e a t o n e :" "<#1F502>")
  (": r e s t r o o m :" "<#1F6BB>")
  (": r e v o l v i n g h e a r t s :" "<#1F49E>")
  (": r i b b o n :" "<#1F380>")
  (": r i c e :" "<#1F35A>")
  (": r i c e b a l l :" "<#1F359>")
  (": r i c e c r a c k e r :" "<#1F358>")
  (": r i c e s c e n e :" "<#1F391>")
  (": r i n g :" "<#1F48D>")
  (": r o c k e t :" "<#1F680>")
  (": r o l l e r c o a s t e r :" "<#1F3A2>")
  (": r o o s t e r :" "<#1F413>")
  (": r o s e :" "<#1F339>")
  (": r o t a t i n g l i g h t :" "<#1F6A8>")
  (": r o u n d p u s h p i n :" "<#1F4CD>")
  (": r o w b o a t :" "<#1F6A3>")
  (": r u :" "<#1F1F7>")
  (": r u g b y f o o t b a l l :" "<#1F3C9>")
  (": r u n n e r :" "<#1F3C3>")
  (": r u n n i n g :" "<#1F3C3>")
  (": r u n n i n g s h i r t w i t h s a s h :" "<#1F3BD>")
  (": s a g i t t a r i u s :" "<#2650>")
  (": s a i l b o a t :" "<#26F5>")
  (": s a k e :" "<#1F376>")
  (": s a n d a l :" "<#1F461>")
  (": s a n t a :" "<#1F385>")
  (": s a t e l l i t e :" "<#1F4E1>")
  (": s a t i s f i e d :" "<#1F606>")
  (": s a x o p h o n e :" "<#1F3B7>")
  (": s c h o o l :" "<#1F3EB>")
  (": s c h o o l s a t c h e l :" "<#1F392>")
  (": s c i s s o r s :" "<#2702>")
  (": s c o r p i u s :" "<#264F>")
  (": s c r e a m :" "<#1F631>")
  (": s c r e a m c a t :" "<#1F640>")
  (": s c r o l l :" "<#1F4DC>")
  (": s e a t :" "<#1F4BA>")
  (": s e e n o e v i l :" "<#1F648>")
  (": s e e d l i n g :" "<#1F331>")
  (": s h a v e d i c e :" "<#1F367>")
  (": s h e e p :" "<#1F411>")
  (": s h e l l :" "<#1F41A>")
  (": s h i p :" "<#1F6A2>")
  (": s h i r t :" "<#1F455>")
  (": s h i t :" "<#1F4A9>")
  (": s h o e :" "<#1F45E>")
  (": s h o w e r :" "<#1F6BF>")
  (": s i g n a l s t r e n g t h :" "<#1F4F6>")
  (": s i x p o i n t e d s t a r :" "<#1F52F>")
  (": s k i :" "<#1F3BF>")
  (": s k u l l :" "<#1F480>")
  (": s l e e p i n g :" "<#1F634>")
  (": s l e e p y :" "<#1F62A>")
  (": s l o t m a c h i n e :" "<#1F3B0>")
  (": s m a l l b l u e d i a m o n d :" "<#1F539>")
  (": s m a l l o r a n g e d i a m o n d :" "<#1F538>")
  (": s m a l l r e d t r i a n g l e :" "<#1F53A>")
  (": s m a l l r e d t r i a n g l e d o w n :" "<#1F53B>")
  (": s m i l e :" "<#1F604>")
  (": s m i l e c a t :" "<#1F638>")
  (": s m i l e y :" "<#1F603>")
  (": s m i l e y c a t :" "<#1F63A>")
  (": s m i l i n g i m p :" "<#1F608>")
  (": s m i r k :" "<#1F60F>")
  (": s m i r k c a t :" "<#1F63C>")
  (": s m o k i n g :" "<#1F6AC>")
  (": s n a i l :" "<#1F40C>")
  (": s n a k e :" "<#1F40D>")
  (": s n o w b o a r d e r :" "<#1F3C2>")
  (": s n o w f l a k e :" "<#2744>")
  (": s n o w m a n :" "<#26C4>")
  (": s o b :" "<#1F62D>")
  (": s o c c e r :" "<#26BD>")
  (": s o o n :" "<#1F51C>")
  (": s o u n d :" "<#1F509>")
  (": s p a c e i n v a d e r :" "<#1F47E>")
  (": s p a d e s :" "<#2660>")
  (": s p a g h e t t i :" "<#1F35D>")
  (": s p a r k l e r :" "<#1F387>")
  (": s p a r k l e s :" "<#2728>")
  (": s p a r k l i n g h e a r t :" "<#1F496>")
  (": s p e a k n o e v i l :" "<#1F64A>")
  (": s p e a k e r :" "<#1F508>")
  (": s p e e c h b a l l o o n :" "<#1F4AC>")
  (": s p e e d b o a t :" "<#1F6A4>")
  (": s t a r :" "<#2B50>")
  (": s t a r 2 :" "<#1F31F>")
  (": s t a r s :" "<#1F320>")
  (": s t a t i o n :" "<#1F689>")
  (": s t a t u e o f l i b e r t y :" "<#1F5FD>")
  (": s t e a m l o c o m o t i v e :" "<#1F682>")
  (": s t e w :" "<#1F372>")
  (": s t r a i g h t r u l e r :" "<#1F4CF>")
  (": s t r a w b e r r y :" "<#1F353>")
  (": s t u c k o u t t o n g u e :" "<#1F61B>")
  (": s t u c k o u t t o n g u e c l o s e d e y e s :" "<#1F61D>")
  (": s t u c k o u t t o n g u e w i n k i n g e y e :" "<#1F61C>")
  (": s u n w i t h f a c e :" "<#1F31E>")
  (": s u n f l o w e r :" "<#1F33B>")
  (": s u n g l a s s e s :" "<#1F60E>")
  (": s u n n y :" "<#2600>")
  (": s u n r i s e :" "<#1F305>")
  (": s u n r i s e o v e r m o u n t a i n s :" "<#1F304>")
  (": s u r f e r :" "<#1F3C4>")
  (": s u s h i :" "<#1F363>")
  (": s u s p e n s i o n r a i l w a y :" "<#1F69F>")
  (": s w e a t :" "<#1F613>")
  (": s w e a t d r o p s :" "<#1F4A6>")
  (": s w e a t s m i l e :" "<#1F605>")
  (": s w e e t p o t a t o :" "<#1F360>")
  (": s w i m m e r :" "<#1F3CA>")
  (": s y m b o l s :" "<#1F523>")
  (": s y r i n g e :" "<#1F489>")
  (": t a d a :" "<#1F389>")
  (": t a n a b a t a t r e e :" "<#1F38B>")
  (": t a n g e r i n e :" "<#1F34A>")
  (": t a u r u s :" "<#2649>")
  (": t a x i :" "<#1F695>")
  (": t e a :" "<#1F375>")
  (": t e l e p h o n e :" "<#260E>")
  (": t e l e p h o n e r e c e i v e r :" "<#1F4DE>")
  (": t e l e s c o p e :" "<#1F52D>")
  (": t e n n i s :" "<#1F3BE>")
  (": t e n t :" "<#26FA>")
  (": t h o u g h t b a l l o o n :" "<#1F4AD>")
  (": t h u m b s d o w n :" "<#1F44E>")
  (": t h u m b s u p :" "<#1F44D>")
  (": t i c k e t :" "<#1F3AB>")
  (": t i g e r :" "<#1F42F>")
  (": t i g e r 2 :" "<#1F405>")
  (": t i r e d f a c e :" "<#1F62B>")
  (": t m :" "<#2122>")
  (": t o i l e t :" "<#1F6BD>")
  (": t o k y o t o w e r :" "<#1F5FC>")
  (": t o m a t o :" "<#1F345>")
  (": t o n g u e :" "<#1F445>")
  (": t o p :" "<#1F51D>")
  (": t o p h a t :" "<#1F3A9>")
  (": t r a c t o r :" "<#1F69C>")
  (": t r a f f i c l i g h t :" "<#1F6A5>")
  (": t r a i n :" "<#1F68B>")
  (": t r a i n 2 :" "<#1F686>")
  (": t r a m :" "<#1F68A>")
  (": t r i a n g u l a r f l a g o n p o s t :" "<#1F6A9>")
  (": t r i a n g u l a r r u l e r :" "<#1F4D0>")
  (": t r i d e n t :" "<#1F531>")
  (": t r i u m p h :" "<#1F624>")
  (": t r o l l e y b u s :" "<#1F68E>")
  (": t r o p h y :" "<#1F3C6>")
  (": t r o p i c a l d r i n k :" "<#1F379>")
  (": t r o p i c a l f i s h :" "<#1F420>")
  (": t r u c k :" "<#1F69A>")
  (": t r u m p e t :" "<#1F3BA>")
  (": t s h i r t :" "<#1F455>")
  (": t u l i p :" "<#1F337>")
  (": t u r t l e :" "<#1F422>")
  (": t v :" "<#1F4FA>")
  (": t w i s t e d r i g h t w a r d s a r r o w s :" "<#1F500>")
  (": t w o h e a r t s :" "<#1F495>")
  (": t w o m e n h o l d i n g h a n d s :" "<#1F46C>")
  (": t w o w o m e n h o l d i n g h a n d s :" "<#1F46D>")
  (": u k :" "<#1F1EC>")
  (": u m b r e l l a :" "<#2614>")
  (": u n a m u s e d :" "<#1F612>")
  (": u n d e r a g e :" "<#1F51E>")
  (": u n l o c k :" "<#1F513>")
  (": u s :" "<#1F1FA>")
  (": v :" "<#270C>")
  (": v e r t i c a l t r a f f i c l i g h t :" "<#1F6A6>")
  (": v h s :" "<#1F4FC>")
  (": v i b r a t i o n m o d e :" "<#1F4F3>")
  (": v i d e o c a m e r a :" "<#1F4F9>")
  (": v i d e o g a m e :" "<#1F3AE>")
  (": v i o l i n :" "<#1F3BB>")
  (": v i r g o :" "<#264D>")
  (": v o l c a n o :" "<#1F30B>")
  (": w a l k i n g :" "<#1F6B6>")
  (": w a n i n g c r e s c e n t m o o n :" "<#1F318>")
  (": w a n i n g g i b b o u s m o o n :" "<#1F316>")
  (": w a r n i n g :" "<#26A0>")
  (": w a t c h :" "<#231A>")
  (": w a t e r b u f f a l o :" "<#1F403>")
  (": w a t e r m e l o n :" "<#1F349>")
  (": w a v e :" "<#1F44B>")
  (": w a v y d a s h :" "<#3030>")
  (": w a x i n g c r e s c e n t m o o n :" "<#1F312>")
  (": w a x i n g g i b b o u s m o o n :" "<#1F314>")
  (": w c :" "<#1F6BE>")
  (": w e a r y :" "<#1F629>")
  (": w e d d i n g :" "<#1F492>")
  (": w h a l e :" "<#1F433>")
  (": w h a l e 2 :" "<#1F40B>")
  (": w h e e l c h a i r :" "<#267F>")
  (": w h i t e c h e c k m a r k :" "<#2705>")
  (": w h i t e c i r c l e :" "<#26AA>")
  (": w h i t e f l o w e r :" "<#1F4AE>")
  (": w h i t e s q u a r e b u t t o n :" "<#1F533>")
  (": w i n d c h i m e :" "<#1F390>")
  (": w i n e g l a s s :" "<#1F377>")
  (": w i n k :" "<#1F609>")
  (": w o l f :" "<#1F43A>")
  (": w o m a n :" "<#1F469>")
  (": w o m a n s c l o t h e s :" "<#1F45A>")
  (": w o m a n s h a t :" "<#1F452>")
  (": w o m e n s :" "<#1F6BA>")
  (": w o r r i e d :" "<#1F61F>")
  (": w r e n c h :" "<#1F527>")
  (": x :" "<#274C>")
  (": y e l l o w h e a r t :" "<#1F49B>")
  (": y e n :" "<#1F4B4>")
  (": y u m :" "<#1F60B>")
  (": z a p :" "<#26A1>")
  (": z z z :" "<#1F4A4>"))

(kbd-map
  ("text ;" (make-folded-comment "comment"))
  ("text :" (make-unfolded-comment "comment")))
