name: build windows
on: push

jobs:
  windowsbuild:
    runs-on: windows-latest
    if: always()
    steps:
      - name: Install msys and xmake
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install:  >-
            mingw-w64-x86_64-xmake 
            mingw-w64-x86_64-make 
            p7zip 
            git 
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          arch: win64_mingw81
          host: 'windows'
          target: 'desktop'
          cache: 'false'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build by mingw
        shell: msys2 {0}
        id: build
        run: |
          /mingw64/bin/xrepo update-repo
          /mingw64/bin/xmake config --yes --plat=mingw --mingw=/c/Qt/Tools/mingw810_64/
          /mingw64/bin/xmake build --yes
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: mogan-windows-dev.exe
          path: |
            build\mingw\x86_64\release\mogan.exe
  linuxbuild:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt update
          sudo apt upgrade --yes gcc
          sudo apt install --yes qtbase5-dev libqt5svg5-dev xmake
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build by gcc
        id: build
        run: |
          xrepo update-repo
          xmake config --yes
          xmake build --yes
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: mogan-windows-dev.exe
          path: |
            .\build\linux\**
  
          