name: mogan.app

on:
  push:
    branches: [ branch-1.2 ]
    paths:
      - '.github/workflows/cd_mogan_app.yml'
      - 'docs/**'
      - 'packages.json'
      - 'yarn.lock'
      - 'site/mogan.app/**'
  workflow_dispatch:

jobs:
  linuxbuild:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: yarn install
      run: yarn install
    - uses: elves/setup-elvish@v1
      with:
        elvish-version: 0.19.2
    - name: build
      run: elvish bin/build_website
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:XmacsLabs/mogan.app.git
        BRANCH: main
        FOLDER: website/
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
