name: research.mogan.app

on:
  push:
    branches: [ branch-1.2 ]
    paths:
      - '.github/workflows/cd_research_mogan_app.yml'
      - 'src/**'
      - '!src/Plugins/Macos/**'
      - '**.lua'
      - bin/config_wasm
      - 'site/research.mogan.app/**'
  workflow_dispatch:

jobs:
  wasmbuild:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    if: always()
    steps:
      - uses: elves/setup-elvish@v1
        with:
          elvish-version: 0.19.2
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.5
      - name: update repo
        run: |
          xrepo update-repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: set XMAKE_GLOBALDIR
        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV
      - name: cache packages from xrepo
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-xrepo-wasm-${{ hashFiles('**/packages.lua') }}
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-xmake-build-${{ hashFiles('**/xmake.lua') }}
      - name: Install Qt wasm
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.3
          arch: wasm_singlethread
          host: 'linux'
          target: 'desktop'
          cache: 'true'
          # workarounds in https://github.com/jurplel/install-qt-action/issues/181
          setup-python: 'false'
          aqtversion: '==3.1.*'
          py7zrversion: '==0.20.*'
          extra: '--autodesktop'
      - name: config
        run: elvish bin/config_wasm
      - name: build
        run: xmake build research
      - name: cp site info
        run: cp site/research.mogan.app/* build/wasm/wasm32/release
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        if: github.event_name != 'pull_request'
        env:
          REPO: git@github.com:XmacsLabs/research.mogan.app.git
          BRANCH: main # The branch name where you want to push the assets
          FOLDER: build/wasm/wasm32/release # The directory where your assets are generated
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
          SQUASH_HISTORY: true
          SSH_PRIVATE_KEY: ${{ secrets.RESEARCH_PRIVATE }}
