name: Build on Archlinux 

on:
  push:
    branches: [ branch-1.2 ]
    paths:
      - 'src/**'
      - '!src/Plugins/Macos/**'
      - '!src/Plugins/Windows/**'
      - 'tests/**'
      - 'misc/xmake/packages.lua'
      - 'xmake.lua'
      - '.github/workflows/ci-archlinux.yml'
  pull_request:
    branches: [ branch-1.2 ]
    paths:
      - 'src/**'
      - '!src/Plugins/Macos/**'
      - '!src/Plugins/Windows/**'
      - 'tests/**'
      - 'misc/xmake/packages.lua'
      - 'xmake.lua'
      - '.github/workflows/ci-archlinux.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    container: archlinux:base-devel
    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Archlinux-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - name: PacMan
        run: |
          sudo pacman -Syyu --noconfirm --needed
          sudo pacman -S --noconfirm --needed qt5-base qt5-svg freetype2 sqlite libpng libiconv zlib libjpeg curl texlive-core python libxext xmake
      - uses: actions/checkout@v1
      - name: Xrepo
        run: XMAKE_ROOT=y;xrepo update-repo
      - name: Config
        run: XMAKE_ROOT=y;xmake config -m release --yes
      - name: Build
        run: XMAKE_ROOT=y;xmake build --yes --verbose --diagnosis --jobs=8 --all
