name: Build on Archlinux 

on:
  push:
    branches: [ branch-1.2 ]
    paths:
      - 'src/**'
      - '!src/Plugins/Macos/**'
      - '!src/Plugins/Windows/**'
      - 'tests/**'
      - 'misc/xmake/packages.lua'
      - 'xmake.lua'
      - '.github/workflows/ci-archlinux.yml'
  pull_request:
    branches: [ branch-1.2 ]
    paths:
      - 'src/**'
      - '!src/Plugins/Macos/**'
      - '!src/Plugins/Windows/**'
      - 'tests/**'
      - 'misc/xmake/packages.lua'
      - 'xmake.lua'
      - '.github/workflows/ci-archlinux.yml'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        kind: [static, shared]

    container: archlinux:base-devel
    runs-on: ${{ matrix.os }}

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Archlinux-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - name: Generate
        run: |
          sudo pacman -Syyu
          sudo pacman -S qt5-base qt5-svg freetype2 sqlite libpng libiconv zlib libjpeg curl texlive-core python libxext
            xrepo update-repo
            xmake config -m release --yes
            xmake build --yes --verbose --diagnosis --jobs=8 --all
      - uses: actions/checkout@v1
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master
          actions-cache-folder: '.xmake-cache'
          actions-cache-key: 'archlinux'
