name: Build on Archlinux 
on:
  push:
    branches: [ branch-1.2 ]
    paths:
      - 'src/**'
      - '!src/Plugins/Macos/**'
      - '!src/Plugins/Windows/**'
      - 'tests/**'
      - 'misc/xmake/packages.lua'
      - 'xmake.lua'
      - '.github/workflows/ci-archlinux.yml'
  pull_request:
    branches: [ branch-1.2 ]
    paths:
      - 'src/**'
      - '!src/Plugins/Macos/**'
      - '!src/Plugins/Windows/**'
      - 'tests/**'
      - 'misc/xmake/packages.lua'
      - 'xmake.lua'
      - '.github/workflows/ci-archlinux.yml'
jobs:
  build:
    strategy:
    container: archlinux:base-devel
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Archlinux-${{ matrix.kind }}
        cancel-in-progress: true
    steps:
      - name: PacMan
        env:
          XMAKE_ROOT: y
        run: |
          sudo pacman -Syyu --noconfirm --needed
          sudo pacman -S --noconfirm --needed qt6-base qt6-svg sqlite libpng zlib libjpeg curl texlive-core python libxext xmake unzip
      - uses: actions/checkout@v1
      - name: Xrepo update
        env:
          XMAKE_ROOT: y
        run: yes | XMAKE_ROOT=y xrepo update-repo
      - name: Config
        env:
          XMAKE_ROOT: y
        run: XMAKE_ROOT=y xmake config -m release --yes
      - name: Build
        env:
          XMAKE_ROOT: y
        run: XMAKE_ROOT=y xmake build --yes --verbose --diagnosis --jobs=8 --all