name: Build via xmake

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  macosbuild:
    runs-on: macos-11
    if: always()
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/.build_cache
            /Users/runner/.xmake
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Dependencies
        run: |
          brew install qt@5
          brew link qt@5
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.7.3
          actions-cache-folder: '.xmake-cache'
      - name: Build by gcc
        id: build
        run: |
          xrepo update-repo
          xmake config --yes
          xmake build --yes --verbose --diagnosis --jobs=8 --all
      - name: Test
        run: |
          xmake run --yes --verbose --diagnosis --group=tests
        env:
          QT_QPA_PLATFORM: offscreen
  windowsbuild:
    runs-on: windows-latest
    if: always()
    steps:
      - name: Install msys and xmake
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          install:  >-
            mingw-w64-x86_64-xmake 
            mingw-w64-x86_64-make 
            p7zip 
            git 
            make 
      - name: Set up MinGW
        uses: coffeebe4code/setup-mingw@v1-beta-2
        with:
          platform: x64
          version: 8.1.0
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          arch: win64_mingw81
          host: 'windows'
          target: 'desktop'
          cache: 'true'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/.build_cache
            C:\Users\runneradmin\AppData\Local\.xmake
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      - name: Build by mingw
        shell: msys2 {0}
        id: build
        run: |
          export PATH=/mingw64/bin/:${Qt5_Dir}/bin/:${PATH}
          xrepo update-repo
          xmake config --yes --verbose --diagnosis --plat=mingw --mingw=/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/ --qt=${Qt5_Dir}
          xmake build --yes --verbose --diagnosis --jobs=8 --all
          windeployqt ./build/mingw/x86_64/release/
          xmake install mogan_install
          windeployqt ./build/package/bin/
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: mogan-windows-dev
          path: |
            build\package\**
      - name: Test
        shell: msys2 {0}
        run: |
          export PATH=/mingw64/bin/:${Qt5_Dir}/bin/:${PATH}
          xmake run --yes --verbose --diagnosis --group=tests
  linuxbuild:
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y gcc qtbase5-dev libqt5svg5-dev qt5-image-formats-plugins
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/.build_cache
            /home/runner/.config/.xmake
          key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.7.3
          actions-cache-folder: '.xmake-cache'
      - name: Build by gcc
        id: build
        run: |
          xrepo update-repo
          xmake config --yes
          xmake build --yes --verbose --diagnosis --jobs=8 --all
      - name: Test
        run: |
          xmake run --yes --verbose --diagnosis --group=tests
        env:
          QT_QPA_PLATFORM: offscreen
  
          