name: Build and Test on mingw

on:
  workflow_dispatch:

jobs:
  windowsbuild:
    # mingw-w64 8.1.0 is installed on windows-2019
    runs-on: windows-2019
    timeout-minutes: 45
    if: always()
    env:
      # Force xmake to a specific folder (for cache)
      XMAKE_GLOBALDIR: "${{ github.workspace }}\\.xmake-global"
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.7
      - name: update repo
        run: |
          xrepo update-repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache packages from xrepo
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ runner.os }}-xrepo-qt-${{ hashFiles('**/packages.lua') }}
      - name: cache xmake
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/build/.build_cache
          key: ${{ runner.os }}-xmake-build-${{ hashFiles('**/xmake.lua') }}
      # Force xmake to a specific folder (for cache)
      - name: Set MinGW for xmake
        run: |
          xmake global --mingw="C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\"
      - name: config
        run: xmake config --policies=build.ccache --yes --verbose --diagnosis -m releasedbg --plat=mingw
      - name: build
        run: xmake build --yes --verbose --diagnosis research && xmake build --yes -vD --group=tests
      - name: test
        run: |
          xmake run --yes --verbose --diagnosis --group=tests
      - name: install
        run: |
          xmake install research
      - name: Scheme tests
        run: xmake run --yes -vD --group=scheme_tests
      - name: integration test in scheme
        run: xmake run --yes -vD --group=integration_tests
        env:
          QT_QPA_PLATFORM: offscreen