name: Deploy devel dir into static page

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: [ branch-1.2 ]
    paths:
      - '.github/workflows/gh-page.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: always()
    continue-on-error: true
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update 
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y gcc \
            fonts-noto-cjk libcurl4-openssl-dev libfreetype-dev \
            qtbase5-dev libqt5svg5-dev qt5-image-formats-plugins

    - name: Set PATH
      run: |
        export TEXMACS_PATH=${{ runner.workspace }}/TeXmacs
        ln -s ${{ runner.workspace }}/plugins ${{ runner.workspace }}/TeXmacs/
    
    - name: set XMAKE_GLOBALDIR
      run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" >> $GITHUB_ENV

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: v2.8.2
        actions-cache-folder: '.xmake-cache'

    - name: xmake repo --update
      run: xmake repo --update

    - name: cache xmake
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
        key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}

    - name: config xmake
      run: xmake config --yes -vD

    - name: BUILD
      run: xmake build tm2html

    - name: generate html
      run: xmake run tm2html -headless -dir devel html-out -q

    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages # The branch name where you want to push the assets
        FOLDER: html-out # The directory where your assets are generated
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        MESSAGE: "Build: ({sha}) {msg}" # The commit message