name: package on macos

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  macosbuild:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 5.15.2
          target: 'desktop'
          cache: 'true'
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.1
          actions-cache-folder: '.xmake-cache'
      - name: xmake repo --update
        run: xmake repo --update
      - name: config
        run: xmake config -m release -vD --yes
      - name: build
        run: xmake build --yes --verbose --diagnosis --all
      - name: install
        run: xmake install -vD mogan
      - name: Generate Installer
        run: |
          xmake install -vD macos_installer
      - name: Upload 
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          path: Mogan-*.dmg
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: Mogan-*.dmg

