name: package on mingw

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  windowsbuild:
    # mingw-w64 8.1.0 is installed on windows-2019
    runs-on: windows-2019
    steps:
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.1
      - name: update repo
        run: |
          xrepo update-repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set MinGW for xmake
        run: |
          xmake global --mingw="C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\"
      - name: config
        run: xmake config --yes -vD -m release --plat=mingw
      - name: build
        run: xmake build -vD mogan
      - name: install
        run: xmake install -vD mogan
      - name: Generate Installer
        run: xmake install -vD windows_installer
      - name: Upload 
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          path: |
            build/*.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: build/*.exe
